easydigitaldownloads/EDD-Commissions

languages/eddc.pot
Using grunt. Check out the pot header!
=> [l18n]> update pot with grunt - add description - header text

includes/EDD_C_List_Table.php, includes/admin/list.php
=> Fixing pagination on filter by status

edd-commissions.php, includes/admin/customers.php
=> Adding commissions data to customer view

includes/short-codes.php
=> Add PayPal email field to profile editor

includes/short-codes.php
=> Additional vendor reports

assets/css/admin-styles.css, includes/EDD_C_List_Table.php, includes/admin/list.php, includes/commission-functions.php
=> Adding better user filtering to commissions list table 

includes/admin/class-batch-commissions-payout.php, includes/admin/list.php
=> Support a minimum payout amount

includes/short-codes.php
=> Add a revoked totals line

includes/admin/widgets.php, includes/commission-functions.php, includes/rest-api.php, includes/short-codes.php
=> Log and identify renewals 

includes/admin/list.php
=> Allow user search to find by paypal email

includes/EDD_C_List_Table.php, includes/admin/list.php
=> Backwards Compat on the exporter 

includes/short-codes.php
It needs to use admin_url to work in the admin for FES
=> Lets export work in the admin

includes/short-codes.php
It doesn't make much sense as a p. Looks out of place like this: http://screencloud.net/v/e82K
=> Change Export Paid Commission to header

includes/short-codes.php
=> Honor shortcode attributes of user_id 

includes/short-codes.php
This makes more sense when viewing someone else's product list
=> Don't use "your" in shortcodes

includes/EDD_C_List_Table.php
=> Improve performance of List Table counts and overall efficiency 

includes/admin/metabox.php
=> Don't convert flat rate commissions less than 1. Fixes #80.

edd-commissions.php, includes/commissions-email-field.php
This adds the commissions field to FES when FES's versions is >= 2.3, thus it can be merged before 2.3 is released as it does a version check
=> Add FES 2.3 Fields API field to Commissions

includes/commissions-email-field.php
Fixes a PHP notice for strict compatibility with defaults for the first variable
=> Fixes PHP notice

includes/commissions-email-field.php
Your guess is as good as mine as why I wrote the commissions field to only show on the frontend, but this PR reverses that design decision and also shows the field and it's values on the admin side
=> Show FES field on admin

includes/settings.php
=> Use EDD 2.5 sections 

includes/reports.php
=> Fix custom date ranges on commission reports 

includes/admin/customers.php
=> adjust Customer UI tab for EDD changes #95

includes/commission-functions.php
=> Avoid undefined variable in eddc_get_recipient_rate 

includes/EDD_C_List_Table.php
@chriscct7 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/easydigitaldownloads/EDD-Commissions/
=> Docbloc fix

assets/css/admin-styles.css, assets/js/admin-scripts.js, includes/admin/class-batch-commissions-mark-paid.php, includes/admin/class-batch-commissions-payout.php, includes/admin/list.php
=> Make generating report and paying commissions 2 steps 

includes/adaptive-payments.php
=> Fix Simple Shipping + PayPal Adaptive + Commissions - Issue/125

includes/admin/class-batch-commissions-payout.php
=> Add user ID to commission payout file for better record keeping. #138

includes/settings.php
=> Fix rich_editor by adding Emails -> commissions subsection #155

includes/admin/widgets.php
=> Fix div ID attr

includes/commission-functions.php, includes/settings.php
=> Add option to revoke unpaid commissions on refund #149 issue/149

includes/EDD_C_List_Table.php, includes/admin/edit.php
=> Issue 171: List and Edit hooks

assets/js/admin-scripts.js, includes/admin/commissions/commissions.php, includes/scripts.php
=> Readd generate payouts button

includes/EDD_C_List_Table.php, includes/admin/commissions/commissions-actions.php, includes/admin/commissions/commissions.php, includes/commission-functions.php
=> First pass at storing rate type data

edd-commissions.php, includes/admin/reporting/export/class-batch-export-commissions-report.php, includes/admin/reporting/export/export-actions.php, includes/admin/reporting/reports.php
=> Initial commission summary export

includes/reports.php
=> issue/82 - Custom date ranges not working properly

assets/js/admin-scripts.js, includes/admin/metabox.php, includes/integrations/recurring-payments.php, includes/integrations/simple-shipping.php
=> Fix saving single user with inherited rate 

includes/admin/classes/class-batch-export-commissions-report.php
=> Only display month/year in CSV 

includes/admin/classes/class-batch-commissions-payout.php
=> Readd user ID row to payout export 

includes/admin/commissions.php
=> Add edit screen hooks #203

includes/admin/commissions.php
=> Readd total commissions display

includes/admin/classes/EDD_C_List_Table.php
=> Remove debugging output

includes/admin/commissions.php
=> Readd user filter

includes/admin/settings.php, includes/commission-actions.php, includes/commission-functions.php
=> Settings for 0.00 commissions

includes/short-codes.php
=> Fix commissions paypal field

includes/admin/classes/EDD_C_List_Table.php
=> Fail gracefully if no users found

includes/admin/classes/EDD_C_List_Table.php, includes/admin/commissions.php, includes/admin/customers.php, includes/admin/metabox.php, includes/admin/widgets.php, includes/commission-functions.php, includes/short-codes.php
=> Add hook to metabox after enable option

includes/commission-functions.php
#226 Check for imporperly saved data and also for products where commissions used to be enabled but now are not.
=> Add empty check and checks for disabled commission

includes/commission-functions.php
Fixes issue with PHP5.3 in #226
=> Move commissions enabled check outside if statement

includes/integrations/recurring-payments.php
=> Change “pay” to “record”

includes/admin/metabox.php
=> Round to allow for currency decimal filter #240

includes/admin/settings.php
=> Fix spelling error from theme to them #232

includes/short-codes.php
=> Add hooks into commissions_overview shortcode #231

includes/admin/commissions.php
=> use is_callable instead of function_exists #228

includes/admin/reports.php
=> Change name of key var to $year (singular)

.travis.yml, includes/commission-functions.php, tests/tests-commission-functions.php
=> Make sure amount exists before we use it #238

languages/eddc.pot
=> Update .pot file #245

assets/css/admin-styles.css, assets/js/admin-scripts.js, includes/admin/classes/EDD_C_List_Table.php, includes/admin/commissions-actions.php, includes/admin/commissions.php, includes/scripts.php
=> Verify empty required inputs and fix up the rates #258

assets/js/admin-scripts.js, includes/admin/classes/class-batch-export-commissions-report-details.php, includes/admin/classes/class-batch-export-commissions-report.php, includes/admin/export-actions.php, includes/admin/export-functions.php, includes/admin/reports.php, includes/classes/class-edd-commission-db.php, includes/scripts.php
=> Add ability to do detailed export with status filters #115

includes/email-functions.php
=> Add commission_id, item_price, and item_tax to commission email tags #237

includes/admin/commissions-actions.php, includes/commission-functions.php
=> Add filter to remove recipients from getting a commission on their own purchase - issue/101

includes/short-codes.php
=> Account for empty download_id in commission record #257

includes/admin/settings.php, includes/classes/class-edd-commission-db.php, includes/commission-functions.php
=> Commissions need to accept float and negative fees affect it #158

includes/admin/classes/EDD_C_List_Table.php, includes/admin/upgrades.php, includes/classes/class-edd-commission-db.php, includes/integrations/wp-cli.php
=> Fix migration to be more fault tolerant of payments, and remove unnecessary methods #134

includes/classes/class-edd-commission-meta-db.php, includes/classes/class-edd-commission.php, includes/commission-filters.php, tests/bootstrap.php, tests/helpers/class-edd-commissions-unittestcase.php, tests/tests-commissionmeta-bc-class.php
=> Adding unit tests for backwards compatible post meta #134
